#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &

bspc monitor -d terminal firefox code files music movie extra

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle false

bspc config focused_border_color "#005D6F"

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a qBittorrent desktop='^2' follow=on
bspc rule -a code-oss desktop='^3'
bspc rule -a Pcmanfm desktop='^4' follow=on
bspc rule -a mpv state=floating desktop='^6' follow=on
bspc rule -a Gimp desktop='^7' state=floating follow=on focus=on
bspc rule -a Screenkey manage=off

polybar mybar &
~/.fehbg
mpd &
picom --config ~/.config/picom/picom.conf &
dunst -config ~/.config/dunst/dunstrc &