#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &

bspc monitor -d terminal firefox code files music movie extra

bspc config top_padding         24
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle false

bspc config focused_border_color "#88c0d0"
bspc config normal_border_color "#4c566a"

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a qBittorrent desktop='^2' follow=on
bspc rule -a code-oss desktop='^3'
bspc rule -a Pcmanfm desktop='^4' follow=on
bspc rule -a mpv state=floating desktop='^6' follow=on
bspc rule -a Gimp-2.10 desktop='^7' follow=on focus=on
bspc rule -a feh state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Screenkey manage=off

polybar mybar &
~/.fehbg
mpd &
dunst &
picom &