#!/usr/bin/env sh
#
# terminal emulator
super + Return
	urxvt

# program launcher
super + @space
	dmenu_run -b -fn "xos4 terminus" -nb "#22222f" -nf "#d8dee9" -sb "#ee7674" -sf "#d8dee9"
	
# apps
super + shift + {b,c,f,m,v}
        {firefox,code,pcmanfm,urxvt -e ncmpcpp,urxvt -e vim}

# brightness keybindings
XF86MonBrightness{Up,Down}
        xbacklight {-inc,-dec} 10

# media keys
XF86Audio{Next,Prev,Play,Stop}
        mpc {next,prev,toggle,stop}

# volume
XF86Audio{RaiseVolume,LowerVolume}
        amixer -q sset Master,0 {'5+','5-'}
XF86AudioMute
        amixer -q sset Master,0 toggle

# system
super + {F1,F2,F3}
        systemctl {poweroff,reboot,suspend}

# lockscreen
super + {F4,F5}
        betterlockscreen {-l,-s} blur

# screenshot keybindings
Print
        scrot '/home/raj/Pictures/Screenshots/%Y-%m-%d-%H-%M-%S.png'
shift + Print
	 scrot -s '/home/raj/Pictures/Screenshots/%Y-%m-%d-%H-%M-%S.png'
ctrl + Print
        scrot -C

# gaps
super + g
    bspc config window_gap 0
super + shift + g
    bspc config window_gap 12

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# quit/restart bspwm
super + shift + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
        bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
        bspc node -s biggest

#
# state/flags
#
yellow
# set the window state
super + {t,shift + t,s,f}
        bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
        bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
        bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
        bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
        bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
        bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
        bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
        bspc wm -h off; \
        bspc node {older,newer} -f; \
        bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
        bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
        bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
        bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
        bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
        bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
        bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
        bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
        bspc node -v {-20 0,0 20,0 -20,20 0}

