#! /bin/sh
sxhkd &
$HOME/.config/polybar/launch.sh &
mpd &
~/.fehbg

bspc monitor -d term web editor files media extra 

bspc config border_width         0
bspc config window_gap          12
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a qBittorrent desktop='^2' follow=on 
bspc rule -a Pcmanfm desktop='^4' follow=on
bspc rule -a mpv desktop='^5' state=fullscreen follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a KeePassXC state=fullscreen follow=on
